language: python
python:
  - "2.7"
  - "3.4"
install:
  - sudo apt-get install -qq uuid-dev swig
  - pip install -r test-requirements.txt
  - pip install .
# command to run tests
script: tests/test-runner
